language: python
sudo: required
python:
    - "2.7"
env: 
    - CKANVERSION=master PGVERSION=9.1
services:
    - redis-server
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script: sh bin/travis-run.sh
after_success:
    - coveralls
